apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://haproxytech.github.io/helm-charts'
    targetRevision: 1.29.2
    helm:
      parameters:
        - name: controller.service.type
          value: LoadBalancer
        - name: controller.logging.level
          value: debug
    chart: kubernetes-ingress
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: haproxy-sys
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
