network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      addresses:
        - IP_HOST/24
      nameservers:
        addresses: [192.168.56.211, 192.168.56.210]
      routes:
        - to: default
          via: 192.168.56.254

