- name: Instalação MetalLB
  hosts: control_plane
  become: true
   

  tasks: 
  - name: 9) Copiar yamls MetalLB
    ansible.builtin.copy:
      src: copia/metallb/
      dest: /home/vagrant/metallb/
      owner: vagrant
      mode: '0644'    