- name: Obter token de junção gerado e unir nó ao control-plane Kubernetes
  hosts: all
  become: true
  vars:
    control_plane_ip: "192.168.56.101"

  tasks:
    - name: Obter token de junção
      shell: kubeadm token create --print-join-command
      register: join_command
      when: inventory_hostname == groups['control_plane'][0]

    - name: Definir a variável join_command em todos os nós
      set_fact:
        join_command: "{{ hostvars[groups['control_plane'][0]]['join_command'] }}"
      when: inventory_hostname in groups['nodes']

    - name: Unir nó ao control-plane
      shell: "{{ join_command.stdout }}"
      when: inventory_hostname in groups['nodes']
